### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by ptykamikaze** [magaya-dev/hyperion-node#4]
When I executed the command to run the node application, it throws an error:

```
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));

...@magaya\hyperion-node\bin\x64\hyperion.node'` was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
```

I searched in the internet and it seems that this problem should be fixed with npm rebuild --update-binary but it is not working.. 

Please help

**Comment by osniel** [comment]
Hi,

Are you sure you are using the package you want? Hyperion is a package to connect to Magaya's database, and it is compiled for Node 8.11, which is different from the one you're using, according to the error message you're getting

**Comment by ptykamikaze** [comment]
I'm sure this is the correct package and yes I want to connect to Magaya... normally, when these errors are presented, the package has to be rebuilt which is not working in your repository ([example from stackoverflow](https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio)).

I have this problem also with the hyperion-express-middleware... How can you close the error if you even didn't wait for my feedback?

**Comment by ptykamikaze** [comment]
Definitely I will continue providing the integration through your wsdl and like always, Magaya Corporation has 0 in customer services... Leave it close, I wont use something that is not working.

**Comment by osniel** [comment]
Those packages are compiled and distributed by Magaya and are not meant to be rebuilt at the client's machine. They're compiled to be compatible with Node 8.11 only, if you want to use them you can use that version of Node.
